export { default as apple } from "./assets/apple.png";
export { default as cart } from "./assets/cart.png";
export { default as google } from "./assets/google.png";
export { default as habitual } from "./assets/habitual.png";
export { default as home } from "./assets/home.png";
export { default as main } from "./assets/main.png";
export { default as orders } from "./assets/orders.png";
export { default as product } from "./assets/product.png";
export { default as profile } from "./assets/profile.png";
